### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by DarthGandalf** [shutter-project/shutter-jekyll-site#11]
They link to non-existing files. The links should either be fixed to /wp-content/ as on old site, or e.g. included as `<video>`

**Comment by Photon89** [comment]
Yep, I uploaded them to the old site but didn't yet to the new one (since they're big and I wanted to make sure that we stick to the site before uploading them again). Will reupload them asap!

**Comment by DarthGandalf** [comment]
I mean, if in long term old URLs will keep working via netlify redirect, it's probably fine to have the old /wp-content/ links there.

It's still better to use `<video>` though than a plain link
