### ISSUE TITLE
Add Netlify badge and CoC

### ISSUE THREAD

**Issue by mheffner** [shutter-project/shutter-jekyll-site#5]
According to: https://www.netlify.com/legal/open-source-policy/

We need:

* Features a Code of Conduct at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).
* Must feature a link to our service on your main page, or all internal pages. You have two options:
  - We have premade badges for your convenience, or
  - You may create your own link, which should read “This site is powered by Netlify”, and include a link back to our home page.

**Comment by vadi2** [comment]
Added now.

**Comment by DarthGandalf** [comment]
Where is CoC?

**Comment by vadi2** [comment]
Good point. Just a moment.

We're also in Jitsi at the moment if you want to join.

**Comment by vadi2** [comment]
See https://github.com/shutter-project/shutter/pull/302
